/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "primary-fixed": "#d8e2ff",
        "on-secondary-fixed": "#001a41",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbcc",
        "inverse-primary": "#adc6ff",
        "tertiary-container": "#c64f00",
        "inverse-surface": "#2e3132",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#004493",
        "on-tertiary-container": "#fffbff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-container": "#fefcff",
        "on-secondary-container": "#2d4c83",
        "primary": "#0058bc",
        "on-surface": "#191c1d",
        "on-background": "#191c1d",
        "surface-dim": "#d9dadb",
        "on-primary-fixed": "#001a41",
        "surface": "#f8f9fa",
        "secondary": "#405e96",
        "surface-tint": "#005bc1",
        "surface-bright": "#f8f9fa",
        "secondary-fixed": "#d8e2ff",
        "on-secondary-fixed-variant": "#26467d",
        "secondary-container": "#a1befd",
        "on-primary": "#ffffff",
        "surface-container": "#edeeef",
        "on-error-container": "#93000a",
        "background": "#f8f9fa",
        "error": "#ba1a1a",
        "outline": "#717786",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#adc6ff",
        "outline-variant": "#c1c6d7",
        "on-tertiary-fixed-variant": "#7c2e00",
        "surface-variant": "#e1e3e4",
        "primary-container": "#0070eb",
        "on-surface-variant": "#414755",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f4f5",
        "tertiary": "#9e3d00",
        "tertiary-fixed-dim": "#ffb595",
        "on-tertiary-fixed": "#351000"
      },
      fontFamily: {
        "headline": ["Lexend", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
